### ISSUE TITLE
Any use cases with data type `Blob`

### ISSUE THREAD

**Issue by mingyc** [WICG/unload-beacon#12]
> setData(data): Set the current beacon data. The data argument would take the same types as the [sendBeacon](https://www.w3.org/TR/beacon/#sec-sendBeacon-method) method’s data parameter. That is, one of [ArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer), [ArrayBufferView](https://developer.mozilla.org/en-US/docs/Web/API/ArrayBufferView), [Blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob), string, [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData), or [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams).

The current setData(data) specifies to support `Blob`. But is there any critical use case to support sending file-like object in unload beacon?

**Comment by philipwalton** [comment]
The `Blob` format is currently supported by `navigator.sendBeacon()`, which this new API is supposed to be an improvement on. If `Blob` is not supported in this new API it could be a blocker for adoption. It would also complicate the polyfill story, which is not ideal.

My suggestion would be to add telemetry data for usage of `Blob` with `navigator.sendBeacon()` and only remove it if usage is near 0.

**Comment by Sora2455** [comment]
Anecdotally I use Blob with sendBeacon to send JSON payloads to the server.

**Comment by mingyc** [comment]
Thanks for all your feedback. The current decision is to still support Blob.
