### ISSUE TITLE
Enable using `gh-pages` branch for displaying the spec

### ISSUE THREAD

**Issue by mingyc** [WICG/unload-beacon#22]
I've created the `gh-pages` branch, but it looks like this repo is not enabled to use it for https://wicg.github.io/unload-beacon

Not quite sure about the process here, but given that we already have [a spec file][1] (although it's not up-to-date with the explainer), should we enable the static page?

I also have a PR ready to setup github workflow to generate the update from *.bs file.

[1]: https://github.com/WICG/unload-beacon/blob/main/index.bs

**Comment by clelland** [comment]
Yes, I think we need someone with admin access to the repo to set that up.

**Comment by yoavweiss** [comment]
Done!! :)
