### ISSUE TITLE
Interactions between timeout, backgroundTimeout, and back-forward cache

### ISSUE THREAD

**Issue by clelland** [WICG/unload-beacon#24]
If a PendingBeacon has both a timeout and backgroundTimeout set, enters the back-forward cache before the foreground timer fires, and is subsequently restored from cache before the backgroundTimeout fires, what state should the beacon be in?

As a concrete example, given this timeline:

t=0: backgroundTimeout set to 500s, timeout set to 500s. Page is in the foreground.
t=300s: Page enters the bfcache
t=400s: Page is restored from the bfcache

In this case, neither timer whould have fired, so the beacon should still be pending. Now, should there be 100s left on the foreground timer? Or would it get reset to 500s again when the page is restored? Or will the foreground timer be cleared when the page enters the bfcache and not restarted when it leaves?

**Comment by clelland** [comment]
As a follow up, consider this timeline as well:

t=0: backgroundTimeout set to 500s, timeout set to 500s. Page is in the foreground.
t=300s: Page enters the bfcache
t=**600s**: Page is restored from the bfcache

In this case, the page is in the cache at the point when the foreground timer would have originally fired. Should we send the beacon at t=500s, even though the page is in the cache? Should it be sent immediately on restore? Or should restoring the page start the 500s again from zero?

**Comment by mingyc** [comment]
Current implementation in Chrome use different timers for `timeout` and `backgroundTimeout`. Specifically, the `timeout`'s timer also works when the page is in bfcache, and is only reset when `timeout` property is updated again. (this is derived from the previous discussion that we want browser to handle the unreliable part of `setTimeout()`)

for example 1:
> Now, should there be 100s left on the foreground timer? Or would it get reset to 500s again when the page is restored? Or will the foreground timer be cleared when the page enters the bfcache and not restarted when it leaves?
Yes. the beacon will be sent out by the foreground timer in 100s.

for example 2:
> Should we send the beacon at t=500s, even though the page is in the cache? Should it be sent immediately on restore? Or should restoring the page start the 500s again from zero?
the beacon is sent out at 500s by the foreground timer (although the page is not in foreground anymore).

**Comment by clelland** [comment]
Thanks, @mingyc -- so the foreground timeout is really an overall timeout, whether the page is foregrounded or not, and the background timeout only takes effect when the page is backgrounded. I'll update the spec to match that behaviour.
