### ISSUE TITLE
`pending`: if a beacon is already discarded by browser, should it become non-pending

### ISSUE THREAD

**Issue by mingyc** [WICG/unload-beacon#28]
One of the privacy requirement is `Beacons are only sent over the same network that was active when the beacon was registered (e.g. if the user goes offline and moves to a new network, discard pending beacons).`

So there will be some cases that users are still holding beacon object, but it's already discarded by browser.

**Comment by fergald** [comment]
I wonder is that requirement too strict. If someone is interested in sniffing networks, they could continuously ping while the page is outside of BFCache. So, it might be reasonable to allow the beacon to send as long as the network is any of the networks that were in use while the page was outside BFCache.

@clelland

**Comment by fergald** [comment]
My suggestion above requires a concept of network identity which is probably not feasible. So here's another suggestion.

We care about not leaking information that the page cannot normally access. So we want to avoid

1. beacon created on network1
2. page goes into bfcache
3. change to network2
4. page is evicted from bfcache
5. beacon is sent on network2

5 is the privacy leak.

I don't think we care about

1. beacon created on network1
2. change to network2
3. beacon is sent on network2

The page could detect network2 by doing a fetch. 3 is not a leak.

So we can detect network changes while in BFCache and mark the beacon as unsendable. If the page is evicted, unsendable beacons will not be sent. If we come back from BFCache, all beacons becomes sendable again. We might want to send some immediately based on timeouts.

**Comment by mingyc** [comment]
When a beacon marked as unsendable, what will happen to its timeout properties?

1. `backgroundTimeout`: the timer for this only starts when a page enters BFCache, and resets/stops after the page leaves BFCache. So it looks like we just stop this timer when its mark as unsendable.
2. `timeout`: the timer for this one can starts whenever the property is updated (which must happen when a page is not yet in BFCache). So after marked as unsendable, the timer will be frozen for the rest of time while a page is in BFCache. Should it be resumed after page leaving BFCache or we just starting over a new timer

**Comment by clelland** [comment]
> Can network environment info be inferred from a beacon HTTP request?

The privacy issue isn't generally about the recipient of the beacon being able to reconstruct the network environment. It's more about the fact that the network operator can see, from a DNS request, or from the HTTP connection itself, that the user agent is connecting to a specific server.

**Comment by Sora2455** [comment]
My understanding was that you could observe that the user's location had changed if e.g. they were on mobile and were now connecting to a different tower, even after the page had closed, by looking at the IP address of the beacon. And that _that_ was the privacy leak.

**Comment by fergald** [comment]
> > Can network environment info be inferred from a beacon HTTP request?
> 
> The privacy issue isn't generally about the recipient of the beacon being able to reconstruct the network environment. It's more about the fact that the network operator can see, from a DNS request, or from the HTTP connection itself, that the user agent is connecting to a specific server.

Thanks, I don't think we were clear on that and we should definitely document it. Is it documented somewhere in the reporting-API or some other doc on privacy and/or network concerns?

I think the idea I suggested is OK for this case too, if you consider that going back to the site with a BFCache miss is definitely going to cause network access to the server. I guess there are some edge cases there, e.g. if the site had a service worker, maybe it would not make any network accesses but that's not reliable.

**Comment by mingyc** [comment]
> > > Can network environment info be inferred from a beacon HTTP request?
> > 
> > The privacy issue isn't generally about the recipient of the beacon being able to reconstruct the network environment. It's more about the fact that the network operator can see, from a DNS request, or from the HTTP connection itself, that the user agent is connecting to a specific server.

Wouldn't this also apply to other types of request, e.g. fetch/XMLHttpRequest? I think they are not dropped even when network changes after a request is made?
> 
> I think the idea I suggested is OK for this case too, if you consider that going back to the site with a BFCache miss is definitely going to cause network access to the server. I guess there are some edge cases there, e.g. if the site had a service worker, maybe it would not make any network accesses but that's not reliable.

So do we still only handle this only when page is in BFCache? It looks like the main concern is from the view of the network provider now.

**Comment by fergald** [comment]
I think we are still unclear about the threat we are protecting against. My understanding is that we are protecting against

1. user is on site.com
2. user navigates away from site.com
3. user gets on their office wifi (where accessing site.com would be a problem)

We should not send a beacon to site.com after 3. However if we keep going and 

4. user hits back to site.com while on office wifi

Then the user cannot have an expectation that the office wifi will not see traffic to site.com.

**Comment by mingyc** [comment]
I created https://github.com/WICG/unload-beacon/issues/30 specifically to discuss about network change.

Closing this issue we'd like to avoid inconsistent `pending` state between browser & renderer processes.
