### ISSUE TITLE
Add a link to the spec from the main repository

### ISSUE THREAD

**Issue by domenic** [WICG/unload-beacon#42]
I could only find https://wicg.github.io/unload-beacon/ by URL-hacking.

Usually I add it over here: 
!["About" section of the GitHub repository front page](https://user-images.githubusercontent.com/617481/195496745-9c5ad6f1-4902-4557-94ff-34e57b133960.png)

Putting it near the top of the README wouldn't hurt either.

**Comment by mingyc** [comment]
@yoavweiss Could you help? I don't have permission to update the About section.

**Comment by yoavweiss** [comment]
Done! Also, you should have permissions to do that now :)

**Comment by mingyc** [comment]
Thanks!
