### ISSUE TITLE
Should `setData(data)` only support POST request

### ISSUE THREAD

**Issue by mingyc** [WICG/unload-beacon#6]
> setData(data): Set the current beacon data. The data argument would take the same types as the [sendBeacon](https://www.w3.org/TR/beacon/#sec-sendBeacon-method) method’s data parameter. That is, one of [ArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer), [ArrayBufferView](https://developer.mozilla.org/en-US/docs/Web/API/ArrayBufferView), [Blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob), string, [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData), or [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams).

The current proposal doesn't differentiate between GET/POST for the beacon data. But most of them just don't make sense for GET request in term of url encoding, e.g. `Blob`, `ArrayBuffer`, `ArrayBufferView`, and `FormData` can contain arbitrary bytes which is difficult to encode in url.

Would it make sense to specify beacon data from `setData(data)` only works for POST?

**Comment by yutakahirano** [comment]
+1. Setting data to GET requests sounds strange to me. Ignoring `setData` calls or even throwing when the method is GET makes sense to me.

**Comment by fergald** [comment]
@yutakahirano You're suggesting that for a GET beacon, you would set the URL only and if you want to update the beacon you don't call `setData`, you create a new beacon with a new URL?

**Comment by mingyc** [comment]
There was another discussion about atomic property updating in #8 where we decided to make `url` immutable. We might want to add a new method for updating url for GET beacon?

**Comment by fergald** [comment]
Yeah, so actually we might want to have 2 different beacons then, one for GET which can update URL and has no `setData`.

**Comment by jdfreder** [comment]
One particularly nice thing about @fergald's suggestion is that the API is explicit, as opposed to restricting calls based on runtime configuration (HTTP method) which is a potential landmine (runtime Error) for anyone who doesn't read the spec closely.

**Comment by fergald** [comment]
@jdfreder yes, for typescript users having 2 separate beacon classes for GET and POST turns a run-time error into a compile-time error.

@yutakahirano 
I hadn't thought about `HEAD` as a method here. Given that the response is never made available, GET and HEAD seem identical (to the page) but I suppose someone might want us to make one or the other in the request. So I guess we should facilitate both but it seems like they would have exactly the same observable behaviour.

Allowing `setUrl` not just `seqQuery` seems more flexible and I don't see a downside.

I was rather surprised to find that there are frameworks out there that use different encodings. For example, some params in Chromium Code Search URLs are `;`-separated. E.g. `l`, `drc` below

https://source.chromium.org/chromium/chromium/src/+/main:content/browser/renderer_host/render_frame_host_impl.h;l=324;drc=af55b5b6ebe03da36d40e71bd733617291c6c9c7

I complained about it once and was told that it comes from the framework they built it on. So we cannot assume that `seqQuery(query: SearchURLParams)` will actually be OK for everyone.
