### ISSUE TITLE
When the user agent sends data should be clarified

### ISSUE THREAD

**Issue by yutakahirano** [WICG/unload-beacon#7]
I read [the README.md](https://github.com/WICG/unload-beacon/blob/main/README.md) and [the design doc](https://docs.google.com/document/d/1QIFUu6Ne8x0W62RKJSoTtZjSd_bIM2yXZSELxdeuTFo/edit#) but it is still unclear to me when the user agent sends data and when it doesn't.

In the design doc, I found this paragraph.

> In the usual case, the ultimate triggering of the beacon send will be a page lifetime event, such as the page being evicted from the BFCache, or the page’s visibility changing. At this time the PendingBeaconHost will indicate to the PendingBeaconNetworkService which beacons need to be sent.

Does this mean the user agent never starts sending beacons without page lifecycle events (and `sendNow` calls)? The description sounds weaker though (it sounds like there are some exceptions), so I want to make sure.

This is very important so I want to make sure before we start implementing property setters.

**Comment by fergald** [comment]
From #13 it seems at least some of the time it will trigger from a timeout. Unclear as yet whether that timeout could occur while the document is active.

**Comment by mingyc** [comment]
In the latest explainer, a PendingBeacon gets sent in one of the following scenario:

1. By Renderer
   1. When JavaScript executes `PendingBeacon.sendNow()`
   2.  When a PendingBeacon's timer of `timeout` property ends.
   3. When the document (where the PendingBeacon was created) enters `hidden` .visibility state, the renderer will sends out every PendingBeacon it has according to individual PendingBeacon's `backgroundTimeout` property.
2. By Browser
   1. When the document is discarded or deleted, the browser process should send out all queued beacons created on that document.
   2. When the associated document's renderer process crashes, the browser process should send out all queued beacon.
   3. When the document is navigated away, on transitioning to `pagehide` state, the browser process should send out all queued beacons from the document. (Neccessary for https://github.com/WICG/unload-beacon/issues/30)

For 2-1 and 2-2, the beacon object in the renderer won't know whether itself is sent or not, but it's not relevant as the document/renderer is already gone.

For 2-3, the state of the beacon object in the renderer needs to be updated.
